URL:
  HOMEPAGE: http://www.zhihu.com
  LOGIN: http://www.zhihu.com/login
  QUESTIONS: http://www.zhihu.com/log/questions
  QUESTION_PREFIX: http://www.zhihu.com

HEADERS:
  BASE:
    Accept: "*/*"
    Accept-Encoding: gzip, deflate
    Accept-Language: en-US,en;q=0.8
    Cache-Control: no-cache
    Connection: keep-alive
    Content-Type: application/x-www-form-urlencoded; charset=UTF-8
    # Host: www.zhihu.com
    # Origin: http://www.zhihu.com
    Pragma: no-cache
    # Referer: http://www.zhihu.com/
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36
    X-Requested-With: XMLHttpRequest

AUTH:
  EMAIL: 你的登陆邮箱
  PASSWORD: 你的登录密码

TIMEOUT:
  QUERY: 10  # 访问超时,单位 "秒"

PAYLOAD:
  QUESTION:
    start:
    offset:
    _xsrf:

OFFSET: 40
